# Generated by Django 5.0.6 on 2024-07-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('anmeld', models.TextField()),
                ('navn', models.CharField(max_length=100)),
                ('kontakt', models.CharField(max_length=150)),
            ],
        ),
    ]
