# Generated by Django 5.0.6 on 2024-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plade', '0002_anmeld'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kugle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('model', models.ManyToManyField(to='plade.model')),
            ],
        ),
    ]
